version: "3.8"

services:
  wardwork_database:
    image: postgres:15
    container_name: wardwork_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wardwork_database
    ports:
      - "5432:5432"
    volumes:
      - wardwork_db_data:/var/lib/postgresql/data

  wardwork_hasura:
    image: hasura/graphql-engine:v2.40.0
    container_name: wardwork_hasura
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://offerhub_admin:offerhub_pass@wardwork_database:5432/wardwork_database
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: offerhub_secret
    depends_on:
      - wardwork_database
    ports:
      - "8080:8080"

  wardwork_backend:
    build: .
    container_name: wardwork_backend
    restart: always
    environment:
      DATABASE_HOST: wardwork_database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: wardwork_database
    depends_on:
      - wardwork_database
    ports:
      - "3001:3001"

  wardwork_minio:
    image: minio/minio
    container_name: wardwork_minio
    restart: always
    ports:
      - "9000:9000"     # MinIO API
      - "9001:9001"     # Web Console
    environment:
      MINIO_ROOT_USER: offerhub_minio
      MINIO_ROOT_PASSWORD: offerhub_minio_secret
    volumes:
      - wardwork_minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  wardwork_db_data: {}
  wardwork_minio_data: {}
